### ISSUE TITLE
timer.c 코드 설계 관련 이슈 

### ISSUE THREAD

**Issue by yujin0124** [Yeram522/W08-Pintos#6]
### 👀 관련 이슈
1. sleep_list 생성 후 초기화 하지 않음
2. wake_up_ticks 값을 설정하기 전에 그 값을 비교하는 list_insert_ordered 함수 호출하였음
3. wake_up_ticks 값을 비교하여 요소를 정렬하는 list_insert_ordered 함수의 인자로 전달할 비교 함수의 구현
4. timer_interrupt 함수에서도 사용해야 하는 세마포어 sleep_control_sem를 timer_sleep 함수 내부 지역변수로 선언함

### ✨ 작업한 내용
1. timer_init 함수 내부에서 list_init 함수 호출하며 인자로 sleep_list를 전달해 초기화 함
```c
void timer_init(void)
{
        //(생략)

	list_init(&sleep_list);

        //(생략)
}
```
2. list_insert_ordered 호출 전에 wake_up_ticks 값을 설정함
```c
void timer_sleep(int64_t ticks)
{
        //(생략)
	current_thread->wake_up_ticks = start + ticks;

	list_insert_ordered(&sleep_list, &current_thread->elem, wake_up_ticks_less, NULL);
        //(생략)
}
```
3. 멤버 변수를 사용해 해당 멤버 변수가 속하는 구조체의 주소를 찾는 list_entry 매크로를 사용해 구현

### 🍰 참고사항
세마포어 sleep_control_sem를 스레드 구조체의 멤버 변수로 만들어야 할 지 협의 필요

**Comment by Yeram522** [comment]
**3.** 비교 함수는 매크로의 Stuct구조체 인자에 `(thread*) 를 전달하여, list_mem 변수로 thread의 포인터를 구할 수 있도록 하였습니다.
``` c
/*매크로 수정*/
#define list_entry(LIST_ELEM, STRUCT, MEMBER)           \
	((STRUCT *) ((uint8_t *) &(LIST_ELEM)->next     \
		- offsetof (STRUCT, MEMBER.next)))

/* 대소 비교 함수 수정 */
static bool
tick_less (const struct list_elem *a_, const struct list_elem *b_,
            void *aux UNUSED) 
{
  const struct thread *a = list_entry (a_, struct thread, elem);
  const struct thread *b = list_entry (b_, struct thread, elem);
  
  return a->wake_up_ticks < b->wake_up_ticks;
}
```

**4.** thread 구조체의 멤버 변수로 추가하기로 함.
``` c
// thread.h에는 threads/sysnc.h 가 포함되어있지 않으므로 헤더 추가 필수!
#include "threads/synch.h" 
```
``` c
struct thread
{
	//(생략)
	enum thread_status status; /* Thread state. */
	char name[16];			   /* Name (for debugging purposes). */
	int priority;			   /* Priority. */
	int64_t wake_up_ticks;	   /* Compare ticks to unblock */
	struct semaphore sleep_control_sem;
	//(생략)
}
```

**Comment by Yeram522** [comment]
@Yeram522  해당 이슈 개인 파일에 적용 완료 했습니다.
1번 ☑️
2번 ☑️
3번 ☑️
4번 ☑️
5번 ☑️

**Comment by noeyxos** [comment]
@noeyxos 해당 이슈 개인 파일에 적용 완료 했습니다.

1번 ☑️
2번 ☑️
3번 ☑️
4번 ☑️
5번 ☑️
